name: task

on:
  push:
    # branches:
      # - master
  # 手动事件
  workflow_dispatch:
  # 计划事件
  schedule:
    # 每天北京时间 9点 运行
    - cron:  '0 1 * * *'


jobs:
  task:
    name: im fine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automation Task
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python ./temperature.py 36.2
          python ./temperature.py -c
          

